# Generated by Django 3.0.4 on 2020-04-01 01:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickeats', '0004_auto_20200331_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('radius', models.IntegerField(default=5000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(40000)])),
                ('price_1', models.BooleanField(default=True)),
                ('price_2', models.BooleanField(default=True)),
                ('price_3', models.BooleanField(default=True)),
                ('price_4', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
